#ifndef PAIRS_LIB_CORO_INTERNAL_ATTRIBUTES_HPP_
#define PAIRS_LIB_CORO_INTERNAL_ATTRIBUTES_HPP_

#ifdef __clang__
#define PAIRS_LIB_INTERNAL_CORO_RETURN_TYPE [[clang::coro_return_type]]
#define PAIRS_LIB_INTERNAL_CORO_WRAPPER [[clang::coro_wrapper]]
#define PAIRS_LIB_INTERNAL_CORO_LIFETIMEBOUND [[clang::coro_lifetimebound]]
#else
#define PAIRS_LIB_INTERNAL_CORO_RETURN_TYPE
#define PAIRS_LIB_INTERNAL_CORO_WRAPPER
#define PAIRS_LIB_INTERNAL_CORO_LIFETIMEBOUND
#endif

#endif // PAIRS_LIB_CORO_INTERNAL_ATTRIBUTES_HPP_
